from .solver.header import Header
from .solver.list import List
from .solver.dataModel import DataModel
from .solver.logTracker import LogTracker
from .solver.const.const import Const
from .solver.symbols.decrement import DecrementSym
from .solver.symbols.increment import IncrementSym
from .solver.symbols.left import LeftSym
from .solver.symbols.right import RightSym
from .solver.symbols.loopEnd import LoopEndSym
from .solver.symbols.loopStart import LoopStartSym
from .solver.symbols.log import LogSym
from .solver.const.val.numeric.compare.equalToSym import equalToSym
from .solver.const.val.numeric.type.toInt import toInt
from .solver.const.val.numeric.compare.equalTo import equalTo
from .solver.const.val.numeric.compare.greaterThan import greaterThan
from .solver.const.val.numeric.arithmetic.plus import plus
from .solver.const.val.numeric.arithmetic.subtract import subtract
from .solver.pointer import Pointer

class Generator(object):

    def __init__(self, n):
        super(Generator, self).__init__()
        self.c = Const()
        self.d = DataModel()
        self.l = LogTracker(n)
        self.p = Pointer(self.c.getZero())
        self.h = Header(self.c.getZero())
        self.list = List([
            IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        RightSym(),
        IncrementSym(),
        RightSym(),
        RightSym(),
        RightSym(),
        RightSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        RightSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        LoopStartSym(),
        RightSym(),
        LoopStartSym(),
        RightSym(),
        RightSym(),
        RightSym(),
        RightSym(),
        RightSym(),
        RightSym(),
        IncrementSym(),
        RightSym(),
        IncrementSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        DecrementSym(),
        LoopEndSym(),
        RightSym(),
        RightSym(),
        RightSym(),
        RightSym(),
        RightSym(),
        RightSym(),
        RightSym(),
        LoopStartSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        IncrementSym(),
        RightSym(),
        RightSym(),
        RightSym(),
        RightSym(),
        RightSym(),
        RightSym(),
        RightSym(),
        DecrementSym(),
        LoopEndSym(),
        LeftSym(),
        LoopStartSym(),
        RightSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        LoopStartSym(),
        DecrementSym(),
        LeftSym(),
        DecrementSym(),
        LoopStartSym(),
        RightSym(),
        RightSym(),
        IncrementSym(),
        RightSym(),
        IncrementSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        DecrementSym(),
        LoopEndSym(),
        RightSym(),
        RightSym(),
        RightSym(),
        LoopStartSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        IncrementSym(),
        RightSym(),
        RightSym(),
        RightSym(),
        DecrementSym(),
        LoopEndSym(),
        IncrementSym(),
        LeftSym(),
        LoopStartSym(),
        RightSym(),
        LoopStartSym(),
        DecrementSym(),
        LoopEndSym(),
        LeftSym(),
        LoopStartSym(),
        DecrementSym(),
        LoopEndSym(),
        LoopEndSym(),
        RightSym(),
        LoopStartSym(),
        LeftSym(),
        LeftSym(),
        LoopStartSym(),
        RightSym(),
        RightSym(),
        RightSym(),
        IncrementSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        DecrementSym(),
        LoopEndSym(),
        RightSym(),
        RightSym(),
        LoopStartSym(),
        DecrementSym(),
        LoopEndSym(),
        LoopEndSym(),
        LeftSym(),
        LeftSym(),
        LoopEndSym(),
        RightSym(),
        RightSym(),
        RightSym(),
        LoopStartSym(),
        RightSym(),
        RightSym(),
        IncrementSym(),
        RightSym(),
        IncrementSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        DecrementSym(),
        LoopEndSym(),
        RightSym(),
        RightSym(),
        RightSym(),
        LoopStartSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        IncrementSym(),
        RightSym(),
        RightSym(),
        RightSym(),
        DecrementSym(),
        LoopEndSym(),
        IncrementSym(),
        LeftSym(),
        LoopStartSym(),
        RightSym(),
        LoopStartSym(),
        DecrementSym(),
        LoopEndSym(),
        LeftSym(),
        LoopStartSym(),
        DecrementSym(),
        LoopEndSym(),
        LoopEndSym(),
        RightSym(),
        LoopStartSym(),
        LeftSym(),
        LeftSym(),
        IncrementSym(),
        RightSym(),
        RightSym(),
        LoopStartSym(),
        DecrementSym(),
        LoopEndSym(),
        LoopEndSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        LoopEndSym(),
        RightSym(),
        RightSym(),
        RightSym(),
        RightSym(),
        RightSym(),
        LoopStartSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        LogSym(),
        LoopStartSym(),
        DecrementSym(),
        LoopEndSym(),
        LoopEndSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        LeftSym(),
        LoopStartSym(),
        DecrementSym(),
        RightSym(),
        DecrementSym(),
        LeftSym(),
        LoopEndSym(),
        RightSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        IncrementSym(),
        LogSym(),
        LoopStartSym(),
        DecrementSym(),
        LoopEndSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        LoopStartSym(),
        RightSym(),
        RightSym(),
        RightSym(),
        IncrementSym(),
        RightSym(),
        IncrementSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        DecrementSym(),
        LoopEndSym(),
        RightSym(),
        RightSym(),
        RightSym(),
        RightSym(),
        LoopStartSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        IncrementSym(),
        RightSym(),
        RightSym(),
        RightSym(),
        RightSym(),
        DecrementSym(),
        LoopEndSym(),
        LeftSym(),
        DecrementSym(),
        LoopStartSym(),
        RightSym(),
        RightSym(),
        LogSym(),
        RightSym(),
        LogSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        LoopStartSym(),
        DecrementSym(),
        LoopEndSym(),
        LoopEndSym(),
        LeftSym(),
        LeftSym(),
        LoopStartSym(),
        RightSym(),
        RightSym(),
        IncrementSym(),
        RightSym(),
        IncrementSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        DecrementSym(),
        LoopEndSym(),
        RightSym(),
        RightSym(),
        RightSym(),
        LoopStartSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        IncrementSym(),
        RightSym(),
        RightSym(),
        RightSym(),
        DecrementSym(),
        LoopEndSym(),
        LeftSym(),
        LeftSym(),
        LoopStartSym(),
        LeftSym(),
        IncrementSym(),
        RightSym(),
        DecrementSym(),
        LoopEndSym(),
        RightSym(),
        LoopStartSym(),
        LeftSym(),
        IncrementSym(),
        RightSym(),
        DecrementSym(),
        LoopEndSym(),
        LeftSym(),
        LeftSym(),
        LeftSym(),
        DecrementSym(),
        LoopEndSym()
        ], 172)

    def solve(self):
        #s = self.h.getSymAt(self.p.get()).getSymbol()
        while True:
            s = self.list.getSymAt(self.p.get()).getSymbol()
            # print(s)
            if equalToSym(s, '>'):
                self.h.inc(self.c.getOne())

            elif equalToSym(s, '<'):
                self.h.dinc(self.c.getOne())

            elif equalToSym(s, '+'):
                self.d.inc(self.c.getOne(), self.h.get())

            elif equalToSym(s, '-'):
                self.d.dinc(self.c.getOne(), self.h.get())

            elif equalToSym(s, '.'):
                if self.l.log(chr(self.d.get(self.h.get()))):
                    break

            elif equalToSym(s, '['):
                if equalTo(toInt(self.d.get(self.h.get())), self.c.getZero()):
                    l = self.c.getOne()
                    while greaterThan(l, self.c.getZero()):
                        self.p.inc(self.c.getOne())
                        c = self.list.getSymAt(self.p.get()).getSymbol()
                        if equalToSym(c, '['):
                            l = toInt(plus(l, self.c.getOne()))
                        elif equalToSym(c, ']'):
                            l = toInt(subtract(l, self.c.getOne()))

            elif equalToSym(s, ']'):
                l = self.c.getOne()
                while greaterThan(l, self.c.getZero()):
                    self.p.dinc(self.c.getOne())
                    c = self.list.getSymAt(self.p.get()).getSymbol()
                    if equalToSym(c, '['):
                        l = toInt(subtract(l, self.c.getOne()))
                    elif equalToSym(c, ']'):
                        l = toInt(plus(l, self.c.getOne()))

                self.p.dinc(self.c.getOne())
            self.p.inc(self.c.getOne())
